import type { AtlasDensity } from './contracts.js'

export type AtlasComponentCategory = 'foundation' | 'input' | 'navigation' | 'display' | 'feedback' | 'composition' | 'ai'

export interface AtlasComponentVisualContract {
  name: string
  category: AtlasComponentCategory
  anatomy: string[]
  states: string[]
  densities: AtlasDensity[]
  semantics: string
  tokens: string[]
}

const allDensities: AtlasDensity[] = ['compact', 'standard', 'comfortable']

export const atlasComponentContracts: AtlasComponentVisualContract[] = [
  { name: 'AtlasProvider', category: 'foundation', anatomy: ['root', 'theme-context', 'density-context', 'locale-context'], states: ['light', 'dark', 'compact', 'standard', 'comfortable'], densities: allDensities, semantics: '为组件树建立唯一主题、密度与语言边界。', tokens: ['color.*', 'control.height.*', 'font.*'] },
  { name: 'AtlasButton', category: 'input', anatomy: ['root', 'icon', 'label', 'spinner'], states: ['default', 'hover', 'focus', 'active', 'loading', 'disabled'], densities: allDensities, semantics: '明确命令，不承担状态展示。', tokens: ['control.height.*', 'radius.control', 'color.action.*', 'color.focus.ring'] },
  { name: 'AtlasInput', category: 'input', anatomy: ['field', 'label', 'control', 'hint'], states: ['default', 'hover', 'focus', 'filled', 'error', 'disabled'], densities: allDensities, semantics: '采集结构化文本，标签保持稳定可见。', tokens: ['control.height.*', 'radius.control', 'color.border.*', 'color.focus.ring'] },
  { name: 'AtlasTextarea', category: 'input', anatomy: ['field', 'label', 'control', 'hint'], states: ['default', 'hover', 'focus', 'filled', 'error', 'disabled'], densities: allDensities, semantics: '采集多行内容，保留稳定标签、帮助与错误区域。', tokens: ['radius.control', 'color.border.*', 'color.focus.ring'] },
  { name: 'AtlasSelect', category: 'input', anatomy: ['field', 'label', 'control', 'hint'], states: ['default', 'hover', 'focus', 'selected', 'error', 'disabled'], densities: allDensities, semantics: '从有限选项中选择，不模拟自由输入。', tokens: ['control.height.*', 'radius.control', 'color.border.*', 'color.focus.ring'] },
  { name: 'AtlasCheckbox', category: 'input', anatomy: ['root', 'native-control', 'indicator', 'label'], states: ['unchecked', 'checked', 'indeterminate', 'focus', 'disabled'], densities: allDensities, semantics: '选择独立选项或批量对象，标签必须可访问。', tokens: ['control.height.*', 'radius.control', 'color.action.*', 'color.focus.ring'] },
  { name: 'AtlasRadioGroup', category: 'input', anatomy: ['group', 'label', 'option', 'indicator'], states: ['unchecked', 'checked', 'focus', 'disabled'], densities: allDensities, semantics: '在少量互斥选项中做唯一选择。', tokens: ['control.height.*', 'color.action.*', 'color.focus.ring'] },
  { name: 'AtlasSwitch', category: 'input', anatomy: ['root', 'track', 'thumb', 'label'], states: ['off', 'on', 'focus', 'disabled'], densities: allDensities, semantics: '即时启用或关闭设置，不用于延迟提交的多选。', tokens: ['control.height.*', 'color.action.*', 'color.focus.ring'] },
  { name: 'AtlasDateInput', category: 'input', anatomy: ['field', 'label', 'control', 'hint'], states: ['empty', 'filled', 'focus', 'error', 'disabled'], densities: allDensities, semantics: '采集具有明确格式和范围的日期。', tokens: ['control.height.*', 'radius.control', 'color.border.*', 'color.focus.ring'] },
  { name: 'AtlasSearchInput', category: 'input', anatomy: ['root', 'icon', 'control', 'clear'], states: ['empty', 'typing', 'submitted', 'focus', 'disabled'], densities: allDensities, semantics: '搜索和筛选内容，不替代普通文本字段。', tokens: ['control.height.*', 'radius.control', 'color.border.*', 'color.focus.ring'] },
  { name: 'AtlasSegmentedControl', category: 'input', anatomy: ['group', 'segment', 'label', 'indicator'], states: ['default', 'hover', 'focus', 'selected', 'disabled'], densities: allDensities, semantics: '切换少量同级模式，选项不宜过多。', tokens: ['control.height.*', 'radius.control', 'color.action.*'] },
  { name: 'AtlasCard', category: 'display', anatomy: ['root', 'header', 'title', 'description', 'body', 'actions'], states: ['default', 'hover', 'selected', 'disabled'], densities: allDensities, semantics: '只承载一个独立对象，禁止卡片嵌套卡片。', tokens: ['radius.panel', 'color.bg.surface', 'color.border.default', 'shadow.surface'] },
  { name: 'AtlasTabs', category: 'navigation', anatomy: ['tablist', 'tab', 'label', 'count', 'indicator'], states: ['default', 'hover', 'focus', 'active', 'disabled'], densities: allDensities, semantics: '切换同层级视图，不能替代主导航。', tokens: ['control.height.*', 'color.action.*', 'color.border.default'] },
  { name: 'AtlasBreadcrumb', category: 'navigation', anatomy: ['nav', 'list', 'item', 'separator', 'current'], states: ['link', 'hover', 'focus', 'current'], densities: allDensities, semantics: '表达页面层级和返回路径，不承担流程进度。', tokens: ['font.size.body', 'color.text.*', 'color.action.*'] },
  { name: 'AtlasPagination', category: 'navigation', anatomy: ['nav', 'previous', 'pages', 'next'], states: ['first', 'middle', 'last', 'focus', 'disabled'], densities: allDensities, semantics: '控制长列表的数据页，不用于步骤流程。', tokens: ['control.height.*', 'radius.control', 'color.action.*'] },
  { name: 'AtlasSteps', category: 'navigation', anatomy: ['list', 'step', 'indicator', 'title', 'connector'], states: ['pending', 'current', 'completed', 'error'], densities: allDensities, semantics: '表达有先后关系的任务进度。', tokens: ['color.action.*', 'color.status.*', 'color.border.default'] },
  { name: 'AtlasDropdown', category: 'navigation', anatomy: ['trigger', 'menu', 'item', 'separator'], states: ['closed', 'open', 'focus', 'disabled', 'danger'], densities: allDensities, semantics: '收纳低频命令，常用主操作保持直接可见。', tokens: ['control.height.*', 'radius.control', 'shadow.overlay'] },
  { name: 'AtlasTable', category: 'display', anatomy: ['wrapper', 'table', 'caption', 'header', 'row', 'cell', 'selection', 'empty'], states: ['data', 'hover', 'selected', 'sorted', 'empty', 'loading'], densities: allDensities, semantics: '扫描和比较结构化数据；选择控件的辅助文案不可见。', tokens: ['table.rowHeight.*', 'radius.panel', 'color.bg.*', 'color.border.default', 'color.action.soft'] },
  { name: 'AtlasTag', category: 'display', anatomy: ['root', 'label', 'remove'], states: ['neutral', 'primary', 'success', 'warning', 'danger', 'removable'], densities: allDensities, semantics: '表达分类或轻量状态，不作为按钮。', tokens: ['radius.control', 'color.status.*', 'color.status.*Soft'] },
  { name: 'AtlasBadge', category: 'display', anatomy: ['root', 'content', 'indicator'], states: ['count', 'dot', 'overflow', 'success', 'warning', 'danger'], densities: allDensities, semantics: '在对象旁表达数量或提醒，不承载完整状态文案。', tokens: ['radius.round', 'color.status.*'] },
  { name: 'AtlasAvatar', category: 'display', anatomy: ['root', 'image', 'fallback'], states: ['image', 'initials', 'loading'], densities: allDensities, semantics: '表达人员身份，不使用 Orb 替代真人或普通账户头像。', tokens: ['radius.round', 'color.action.soft', 'color.text.*'] },
  { name: 'AtlasStatistic', category: 'display', anatomy: ['root', 'label', 'value', 'suffix', 'trend'], states: ['up', 'down', 'flat'], densities: allDensities, semantics: '突出一个可比较的关键指标，不代替完整图表。', tokens: ['font.size.title', 'color.text.*', 'color.status.*'] },
  { name: 'AtlasProgress', category: 'display', anatomy: ['root', 'label', 'track', 'bar', 'value'], states: ['primary', 'success', 'warning', 'danger'], densities: allDensities, semantics: '表达零到一百的可量化进度。', tokens: ['radius.round', 'color.action.*', 'color.status.*'] },
  { name: 'AtlasAlert', category: 'feedback', anatomy: ['root', 'icon', 'content', 'title', 'description', 'close'], states: ['info', 'success', 'warning', 'danger', 'closable'], densities: allDensities, semantics: '呈现需要用户注意且可解释的反馈。', tokens: ['radius.panel', 'color.status.*', 'color.status.*Soft'] },
  { name: 'AtlasTooltip', category: 'feedback', anatomy: ['trigger', 'surface', 'content'], states: ['hidden', 'hover', 'focus'], densities: allDensities, semantics: '解释陌生图标或术语，不放关键业务信息。', tokens: ['radius.control', 'color.bg.elevated', 'shadow.overlay'] },
  { name: 'AtlasEmpty', category: 'feedback', anatomy: ['root', 'visual', 'title', 'description', 'action'], states: ['without-action', 'with-action'], densities: allDensities, semantics: '解释无数据原因并提供合理下一步。', tokens: ['color.text.*', 'space.*'] },
  { name: 'AtlasSkeleton', category: 'feedback', anatomy: ['root', 'line'], states: ['one-line', 'multi-line', 'reduced-motion'], densities: allDensities, semantics: '加载时保持最终布局稳定，不模拟无关装饰。', tokens: ['color.bg.subtle', 'motion.base'] },
  { name: 'AtlasDialog', category: 'feedback', anatomy: ['backdrop', 'surface', 'header', 'body', 'footer', 'close'], states: ['closed', 'open', 'focus-trapped'], densities: allDensities, semantics: '用于必须集中决策的模态任务，打开后管理焦点。', tokens: ['radius.overlay', 'color.bg.elevated', 'shadow.overlay'] },
  { name: 'AtlasDrawer', category: 'feedback', anatomy: ['backdrop', 'surface', 'header', 'body', 'close'], states: ['closed', 'open', 'focus-trapped'], densities: allDensities, semantics: '保留主页面上下文时查看或编辑次级详情。', tokens: ['color.bg.elevated', 'shadow.overlay'] },
  { name: 'AtlasObjectCell', category: 'composition', anatomy: ['root', 'icon', 'content', 'title', 'meta', 'description'], states: ['default', 'interactive', 'disabled'], densities: allDensities, semantics: '为表格和列表建立稳定的对象视觉锚点。', tokens: ['icon.object.size', 'radius.control', 'color.text.*'] },
  { name: 'AtlasStatusTag', category: 'composition', anatomy: ['root', 'indicator', 'label'], states: ['neutral', 'info', 'success', 'warning', 'danger'], densities: allDensities, semantics: '只表达可解释的业务或系统状态。', tokens: ['color.status.*', 'color.status.*Soft'] },
  { name: 'AtlasRowActions', category: 'composition', anatomy: ['group', 'action', 'overflow'], states: ['default', 'hover', 'focus', 'disabled'], densities: allDensities, semantics: '承载行级命令，图标按钮必须有可访问名称。', tokens: ['control.height.*', 'radius.control', 'color.focus.ring'] },
  { name: 'AtlasTableToolbar', category: 'composition', anatomy: ['root', 'search', 'filters', 'selection', 'actions'], states: ['default', 'filtered', 'selection', 'disabled'], densities: allDensities, semantics: '筛选、批量操作与表格共享一个连续数据表面。', tokens: ['control.height.*', 'color.bg.surface', 'color.border.default'] },
  { name: 'AtlasDataTable', category: 'composition', anatomy: ['root', 'header', 'toolbar', 'table', 'footer'], states: ['data', 'filtered', 'selection', 'empty', 'loading'], densities: allDensities, semantics: '企业数据管理的标准组合配方。', tokens: ['radius.panel', 'table.rowHeight.*', 'color.bg.*', 'shadow.surface'] },
  { name: 'AtlasPageHeader', category: 'composition', anatomy: ['root', 'breadcrumb', 'eyebrow', 'title', 'description', 'actions'], states: ['default', 'with-actions', 'compact'], densities: allDensities, semantics: '建立页面层级与主操作，不承担营销 Hero。', tokens: ['font.size.title', 'color.text.*', 'color.border.default'] },
  { name: 'AtlasPanel', category: 'composition', anatomy: ['root', 'header', 'title', 'description', 'actions', 'body'], states: ['default', 'flush', 'loading'], densities: allDensities, semantics: '承载一组紧密相关信息，禁止再包裹同级卡片外壳。', tokens: ['radius.panel', 'color.bg.surface', 'color.border.default', 'shadow.surface'] },
  { name: 'AtlasOrb', category: 'ai', anatomy: ['atmosphere', 'primary-ring', 'secondary-ring', 'core', 'depth', 'caustic', 'liquid', 'specular'], states: ['idle', 'thinking', 'running', 'error', 'without-ring'], densities: allDensities, semantics: '只表达 AI 身份和生命状态，不作为普通业务图标。', tokens: ['color.brand.*', 'motion.living', 'shadow.orb'] },
  { name: 'AtlasAIComposer', category: 'ai', anatomy: ['contexts', 'editor', 'suggestions', 'toolbar', 'submit'], states: ['empty', 'focus', 'context', 'suggestion', 'busy', 'error'], densities: allDensities, semantics: '承载自然语言目标、上下文和工具执行入口。', tokens: ['radius.panel', 'color.action.*', 'color.focus.ring'] }
  ,{ name: 'AtlasExecutionPlan', category: 'ai', anatomy: ['root', 'header', 'step-list', 'step', 'controls'], states: ['pending', 'running', 'completed', 'failed', 'approval'], densities: allDensities, semantics: '展示 Agent 计划、进度和需要人工介入的步骤。', tokens: ['color.action.*', 'color.status.*', 'color.border.default'] }
  ,{ name: 'AtlasAIConversation', category: 'ai', anatomy: ['root', 'header', 'message-stream', 'composer'], states: ['idle', 'thinking', 'running', 'error'], densities: allDensities, semantics: '组织完整 AI 会话，不隐藏模型状态与上下文。', tokens: ['color.bg.*', 'color.border.default', 'shadow.surface'] }
  ,{ name: 'AtlasAIMessageBubble', category: 'ai', anatomy: ['root', 'avatar', 'meta', 'content', 'citations', 'actions'], states: ['user', 'assistant', 'system', 'tool', 'streaming'], densities: allDensities, semantics: '区分用户、助手、系统和工具消息，并承载证据与操作。', tokens: ['radius.panel', 'color.bg.*', 'color.action.soft'] }
  ,{ name: 'AtlasAIStreamingText', category: 'ai', anatomy: ['root', 'content', 'cursor', 'status'], states: ['streaming', 'complete', 'stopped', 'error'], densities: allDensities, semantics: '表达生成中的增量文本和最终状态。', tokens: ['color.text.*', 'color.status.*', 'motion.base'] }
  ,{ name: 'AtlasAIPrompts', category: 'ai', anatomy: ['group', 'prompt', 'category', 'description'], states: ['default', 'hover', 'focus', 'disabled'], densities: allDensities, semantics: '提供可解释的起始问题和快捷指令。', tokens: ['radius.control', 'color.action.soft', 'color.focus.ring'] }
  ,{ name: 'AtlasAIAttachmentList', category: 'ai', anatomy: ['list', 'item', 'type', 'name', 'progress', 'actions'], states: ['ready', 'uploading', 'failed', 'removable'], densities: allDensities, semantics: '展示进入 AI 上下文的附件、状态和移除控制。', tokens: ['radius.control', 'color.bg.subtle', 'color.status.*'] }
  ,{ name: 'AtlasAIConversationHistory', category: 'ai', anatomy: ['root', 'create', 'list', 'item', 'preview', 'pin'], states: ['active', 'pinned', 'hover', 'focus'], densities: allDensities, semantics: '管理会话选择与最近上下文，不承担消息正文。', tokens: ['color.action.soft', 'color.border.default', 'control.height.*'] }
  ,{ name: 'AtlasAIFeedback', category: 'ai', anatomy: ['root', 'helpful', 'unhelpful', 'report'], states: ['empty', 'helpful', 'unhelpful', 'reported'], densities: allDensities, semantics: '收集回答质量反馈并提供问题上报。', tokens: ['control.height.*', 'color.action.*', 'color.status.*'] }
  ,{ name: 'AtlasMCPServerPicker', category: 'ai', anatomy: ['root', 'server-list', 'server', 'status', 'transport', 'tools'], states: ['connected', 'disconnected', 'selected', 'disabled'], densities: allDensities, semantics: '明确 Agent 可使用的 MCP Server、传输与授权范围。', tokens: ['radius.panel', 'color.status.*', 'color.border.default'] }
  ,{ name: 'AtlasCitationList', category: 'ai', anatomy: ['list', 'citation', 'index', 'title', 'excerpt', 'confidence'], states: ['default', 'interactive', 'low-confidence'], densities: allDensities, semantics: '展示 AI 结果的可追溯来源和相关度。', tokens: ['radius.control', 'color.action.soft', 'color.text.*'] }
  ,{ name: 'AtlasKnowledgeSourcePicker', category: 'ai', anatomy: ['group', 'source', 'type', 'status', 'scope', 'selection'], states: ['ready', 'syncing', 'error', 'selected'], densities: allDensities, semantics: '选择可检索知识源并显式呈现权限范围。', tokens: ['radius.panel', 'color.status.*', 'color.border.default'] }
  ,{ name: 'AtlasRetrievalTrace', category: 'ai', anatomy: ['root', 'step-list', 'step', 'duration', 'status'], states: ['pending', 'running', 'completed', 'failed'], densities: allDensities, semantics: '解释查询、检索、过滤、重排和引用形成过程。', tokens: ['color.action.*', 'color.status.*', 'color.border.default'] }
  ,{ name: 'AtlasToolCallCard', category: 'ai', anatomy: ['root', 'header', 'permission', 'input', 'result', 'controls'], states: ['queued', 'running', 'approval', 'completed', 'failed'], densities: allDensities, semantics: '呈现工具权限、输入输出、审批、失败和重试。', tokens: ['radius.panel', 'color.status.*', 'color.border.default', 'shadow.surface'] }
]

export const atlasVisualRules = {
  contractVersion: '0.2.0-beta.2',
  maxContentRadius: 8,
  tableRowHeight: { compact: 36, standard: 42, comfortable: 50 },
  orbAllowedContexts: ['ai-assistant', 'agent-identity', 'ai-generation', 'ai-execution', 'ai-governance'],
  requiredThemes: ['light', 'dark'],
  requiredLocales: ['zh-CN', 'en-US'],
  requiredDensities: allDensities
} as const
