create table atlas_audit_events (
  id bigint generated by default as identity primary key,
  tenant_id varchar(80) not null,
  actor varchar(120) not null,
  action varchar(120) not null,
  resource_type varchar(80) not null,
  resource_id varchar(160) not null,
  outcome varchar(40) not null,
  details varchar(4000) not null,
  correlation_id varchar(80) not null,
  created_at timestamp with time zone not null
);

create index idx_atlas_audit_tenant_time on atlas_audit_events (tenant_id, created_at);

create table atlas_agent_executions (
  id varchar(36) primary key,
  tenant_id varchar(80) not null,
  actor varchar(120) not null,
  tool_name varchar(120) not null,
  status varchar(40) not null,
  input_json varchar(4000) not null,
  result_json varchar(4000),
  approved_by varchar(120),
  approved_at timestamp with time zone,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);

create index idx_atlas_agent_tenant_time on atlas_agent_executions (tenant_id, created_at);
