create table atlas_ai_usage (
  id bigint generated by default as identity primary key,
  tenant_id varchar(80) not null,
  actor varchar(120) not null,
  request_id varchar(80) not null,
  provider varchar(80) not null,
  model varchar(120) not null,
  input_tokens integer not null,
  output_tokens integer not null,
  estimated_cost_micros bigint not null,
  attempts integer not null,
  duration_ms bigint not null,
  outcome varchar(40) not null,
  created_at timestamp with time zone not null
);

create index idx_atlas_ai_usage_tenant_time on atlas_ai_usage (tenant_id, created_at);

create table atlas_ai_conversations (
  id varchar(36) primary key,
  tenant_id varchar(80) not null,
  actor varchar(120) not null,
  title varchar(240) not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);

create unique index uk_atlas_ai_conversation_tenant on atlas_ai_conversations (tenant_id, id);

create table atlas_ai_messages (
  id varchar(36) primary key,
  conversation_id varchar(36) not null,
  tenant_id varchar(80) not null,
  role varchar(40) not null,
  content varchar(12000) not null,
  metadata varchar(4000) not null,
  created_at timestamp with time zone not null,
  constraint fk_atlas_ai_message_conversation foreign key (conversation_id) references atlas_ai_conversations(id) on delete cascade
);

create index idx_atlas_ai_message_conversation_time on atlas_ai_messages (tenant_id, conversation_id, created_at);

create table atlas_ai_attachments (
  id varchar(36) primary key,
  conversation_id varchar(36) not null,
  tenant_id varchar(80) not null,
  file_name varchar(240) not null,
  media_type varchar(120) not null,
  storage_key varchar(500) not null,
  size_bytes bigint not null,
  created_at timestamp with time zone not null,
  constraint fk_atlas_ai_attachment_conversation foreign key (conversation_id) references atlas_ai_conversations(id) on delete cascade
);

create index idx_atlas_ai_attachment_conversation on atlas_ai_attachments (tenant_id, conversation_id);
